# Generated by Django 2.1 on 2018-10-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_imeges/default_product.png', upload_to='product_imeges'),
        ),
    ]
